version: "2"

services:
  factorio:
    image: factoriotools/factorio
    restart: unless-stopped
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ./factorio:/factorio
